// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erqwmijnuztbkqhlupge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVycXdtaWpudXp0YmtxaGx1cGdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1Nzg1MjUsImV4cCI6MjA3MzE1NDUyNX0.SvbIvHC4iV8jOLpiKhcZgksI67wVIHZ5Ngi8vZxwmOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});